-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D INNER JOIN SKILLCODES AS S
ON D.SKILL_CODE & S.CODE >0
WHERE S.NAME IN ("PYTHON","C#")
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY D.ID;